default["rackspace-user"]["user"] = 'rack'
default["rackspace-user"]["password_hash"] = '$6$80zp1wddO5pTaGHU$Q55OVyymFue2sS1OruznrDkoXu/QLl8p3R3ki24ktl52x90blodxqPldo3o8B5PHfBppJTmyEh2ljTJrjdO/M/'
default["rackspace-user"]["remote_file"] = 'https://raw.github.com/rackops/authorized_keys/master/authorized_keys'
default["rackspace-user"]["shell"] = '/bin/bash'
default["rackspace-user"]["home_folder"] = '/home/rack'
